* Amazon AWS notes
- if logging into my machine for the first time make sure to
  *export SSEC2_PROFILE=layerlab*

** Preparing the instance
*** Launching an i3.large instance
- *ssec2 launch -t i3.large*
- -t is the type of instance
  
*** Connecting to the instance
- *ssec2 connect -l* to list the running instances
- *ssec2 connect -i name_of_instance*

*** Preparation Script
- after launching an instance of i3.large run the following
  *bash <(curl -s http://layerlab.org/aws/i3.sh)*

- (maybe run with *sudo*)

  This is just downloading a script hosted on Ryan's website and executing it
  in order to prepare instance with various bits of software.

- DONE look into the contents of the script and see if I can add some stuff 
  in there.  Maybe I should just download a local copy for my self and put
  on the git repo.
  
*** Install mosdepth
- install from
  https://github.com/brentp/mosdepth/releases/download/v0.2.4/mosdepth

- Just use *wget* to download the binary to desired location 
  */mnt/local/bin* will have been created during the setup script

- make sure it's on your path
  
- make sure to *chmod +x mosdepth*
  
*** Command to run on instance once everything is setup
aws s3 cp s3://1000genomes/phase1/phase1.exome.alignment.index - |  tail -n+2 | gargs -p 10 'bash bam_processing.sh {0}'
  


** Extracting signal
- use the following command to run the get_exons.sh script with gargs
  cat 20120518.consensus_add50bp.bed | gargs --log get_exons.log -o -p 4 "bash get_exons.sh {0} {1} {2} HG00096.per-base.bed.gz" > output.txt
  
* Get Samples with a per-base.bed.gz.csi from the exome dir
tr -s ' ' < exome-dir.txt | cut -d ' ' -f4 | cut -d '.' -f1 | uniq > samples.txt

  
* bcftools notes
** command for deletions
*** TODO Understand each part of this command so I can modify if necessary.
bcftools view -s HG00096 -c 1 -i 'SVTYPE="DEL"' $VCF | \
bcftools query -f 'CHROM\t%POS\t%INFO/END\t[%GT]\n' | \
bedtools intersect -wao stdin -a HG00096.regions.bed.gz -f 0.5 | \
awk '{OFS="\t"; o=$8; if (o==".") {o="0|0";}  print $1,$2,$3,o}' 
